import { IExecuteFunctions } from 'n8n-core';
import {
	INodeExecutionData,
	INodeType,
	INodeTypeDescription,
	INodePropertyOptions,
} from 'n8n-workflow';

export class Figma implements INodeType {
	description: INodeTypeDescription = {
		displayName: 'Figma',
		name: 'figma',
		group: ['transform'],
		version: 1,
		description: 'Basic Figma node',
		defaults: {
			name: 'Figma',
			color: '#772244',
		},
		inputs: ['main'],
		outputs: ['main'],
		properties: [
			// Node properties which the user can configure
			// which are displayed in the editor
			{
				displayName: 'Figma Webhook URL',
				name: 'figmaWebhookUrl',
				type: 'string',
				default: '',
				placeholder: 'Paste your Figma webhook URL here',
				description: 'The webhook URL generated by the Figma plugin',
			},
			{
				displayName: 'Image URL',
				name: 'imageUrl',
				type: 'string',
				default: '',
				description: 'The URL of the image to be placed in Figma',
			},
			{
				displayName: 'Text Content',
				name: 'textContent',
				type: 'string',
				default: '',
				description: 'The text to be placed in Figma',
			},
			{
				displayName: 'X Coordinate',
				name: 'x',
				type: 'number',
				default: 0,
				description: 'The x-coordinate of the image and text',
			},
			{
				displayName: 'Y Coordinate',
				name: 'y',
				type: 'number',
				default: 0,
				description: 'The y-coordinate of the image and text',
			},
		],
	};

	async execute(this: IExecuteFunctions): Promise<INodeExecutionData[][]> {
		const items = this.getInputData();
		let item: INodeExecutionData;
		let figmaWebhookUrl: string;
		let imageUrl: string;
		let textContent: string;
		let x: number;
		let y: number;

		for (let itemIndex = 0; itemIndex < items.length; itemIndex++) {
			try {
				figmaWebhookUrl = this.getNodeParameter('figmaWebhookUrl', itemIndex, '') as string;
				imageUrl = this.getNodeParameter('imageUrl', itemIndex, '') as string;
				textContent = this.getNodeParameter('textContent', itemIndex, '') as string;
				x = this.getNodeParameter('x', itemIndex, 0) as number;
				y = this.getNodeParameter('y', itemIndex, 0) as number;

				const options = {
					method: 'POST',
					uri: figmaWebhookUrl,
					body: {
						imageUrl,
						textContent,
						x,
						y,
					},
					json: true,
				};

				await this.helpers.request(options);
			} catch (error) {
				if (this.continueOnFail()) {
					items.push({ json: this.getInputData(itemIndex)[0].json, error, pairedItem: itemIndex });
				} else {
					if (error.context) {
						error.context.itemIndex = itemIndex;
						throw error;
					}
					throw new Error(`Figma node error: ${error.message}`);
				}
			}
		}

		return [this.helpers.returnJsonArray(items)];
	}
}
